### ISSUE TITLE
./byfn.sh up SERVICE_UNAVAILABLE error

### ISSUE THREAD

**Issue by catarinaurgueira** [keenkit/fabric-sample-with-kafka#2]
Hello,

I downloaded and tried to run your code without any changes but when I ran the command to execute the E2E test it gave me an error of SERVICE_UNAVAILABLE:

![screenshot 33](https://user-images.githubusercontent.com/26204088/41676107-7de92c4c-74bc-11e8-9b40-6192958c9263.png)

Do you know how can I solve this?
Thank you

**Comment by will-hu-0** [comment]
Hey @catarinaurgueira , looks like it is a similar case as [https://github.com/keenkit/fabric-sample-with-kafka/issues/1](https://github.com/keenkit/fabric-sample-with-kafka/issues/1), I provided the check list into the response from that thread, wondering if you may check it as well to drill down the root cause? 
Thanks.

**Comment by catarinaurgueira** [comment]
Hello @keenkit  I solved the problem by adding more time to the sleep of byfn.sh file.
I'm trying to build a network with three organizations and two orderers and I'm using Kafka.

In the script.sh file there's a method called createChannel() that runs the following command: 
` peer channel create -o orderer.example.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/channel.tx --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem >&log.tx`

I can already join the peers from both of the three organizations.

Do you know how can I create a channel with two orderers? Or how can I add an orderer to an existing channel?

**Comment by catarinaurgueira** [comment]
Hello @keenkit I solved the problem by adding more time to the sleep of byfn.sh file.
I'm trying to build a network with three organizations and two orderers and I'm using Kafka.

In the script.sh file there's a method called createChannel() that runs the following command:
peer channel create -o orderer.example.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/channel.tx --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem >&log.tx

I can already join the peers from both of the three organizations.

Do you know how can I create a channel with two orderers? Or how can I add an orderer to an existing channel?
Thank you

**Comment by will-hu-0** [comment]
Hey @catarinaurgueira , good to hear that the issue resolved.
*A channel with two orderers*, the example is with 2 orderers, can you clarify more on the question please?

**Comment by catarinaurgueira** [comment]
Hello @keenkit , I just wanna know how can I run the network with a channel with two orderers, because on ./byfn.sh file the channel is created with just one peer.   

Thank you

**Comment by catarinaurgueira** [comment]
Hello @keenkit , I just wanna know how can I run the network with a channel with two orderers, because on ./byfn.sh file the channel is created with just one orderer.

Thank you

**Comment by will-hu-0** [comment]
Hi @catarinaurgueira , I got what you mean here. In the scripts/script.sh file, it only touches orderer0, however when I check the logs from orderer1/2, looks like they share the same information. I have not drilled down to that part yet.. Need to verify it with deploying the network onto different VMs. I will on it very shortly.

**Comment by nico13051995** [comment]
@catarinaurgueira Hi, what kind of changes did you make, I've paused in a few places and nothing. Could you attach a file or something like that?
